# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-11-14 12:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='info',
            field=models.CharField(default='', max_length=256, verbose_name='个人签名'),
        ),
    ]
