# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-11-09 02:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discuss', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='discuss',
            name='parent_id',
            field=models.IntegerField(default=0, verbose_name='父评论ID'),
        ),
    ]
