# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-11-09 03:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discuss', '0002_discuss_parent_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discuss',
            name='music_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.Music'),
        ),
        migrations.AlterField(
            model_name='discuss',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.User'),
        ),
    ]
