# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-11-11 12:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discuss', '0003_auto_20191109_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='discuss',
            name='created_time',
            field=models.DateTimeField(auto_now=True, verbose_name='评论时间'),
        ),
    ]
