# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-10-28 05:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Musician',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('musician', models.CharField(max_length=10, verbose_name='歌手')),
                ('music_name', models.CharField(max_length=6, verbose_name='歌名')),
                ('music', models.FileField(upload_to='static/images', verbose_name='音乐路径')),
                ('style', models.IntegerField(choices=[(1, '流行'), (2, '摇滚'), (3, '电子'), (4, '民谣'), (5, '爵士'), (6, '其他')], default=1, verbose_name='风格')),
                ('picture', models.ImageField(upload_to='static/images', verbose_name='图片路径')),
                ('like', models.IntegerField(verbose_name='喜欢')),
                ('addtime', models.DateTimeField(auto_now=True, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '音乐',
                'verbose_name_plural': '音乐',
                'db_table': 'musician',
            },
        ),
    ]
