# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-11-14 10:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musician', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='musician',
            options={'verbose_name': '音乐人', 'verbose_name_plural': '音乐人'},
        ),
    ]
