# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-10-28 12:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='discuss_user',
            field=models.ManyToManyField(to='users.User'),
        ),
    ]
