# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-11-21 12:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_music_discuss_user'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='music',
            table='music_music',
        ),
    ]
