# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-11-21 12:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_auto_20191121_2029'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='music',
            table=None,
        ),
    ]
