# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-11-21 13:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_user_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person_diary',
            fields=[
                ('diary_id', models.AutoField(auto_created=True, max_length=20, primary_key=True, serialize=False, verbose_name='编号')),
                ('content', models.CharField(max_length=500, verbose_name='日记内容')),
                ('created_time', models.DateTimeField(auto_now_add=True, max_length=30, verbose_name='创建时间')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.User')),
            ],
            options={
                'db_table': 'person_diary',
            },
        ),
        migrations.CreateModel(
            name='Person_photo',
            fields=[
                ('photo_id', models.AutoField(auto_created=True, max_length=20, primary_key=True, serialize=False, verbose_name='照片编号')),
                ('avatar', models.ImageField(default='', upload_to='avatar', verbose_name='头像')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.User')),
            ],
            options={
                'db_table': 'person_photo',
            },
        ),
    ]
